# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            field noise
tagline:          'sound | nature | technology'
description:      'sound | nature | tech<br>A blog by <a href="http://craigeley.com">Craig Eley</a>'
url:              http://fieldnoise.com
baseurl:          http://craigeley.github.io/fieldnoise-site/

author:
  name:           'Craig Eley'
  url:            http://craigeley.github.io/fieldnoise-site/

paginate:         5

# Custom vars
version:          2.0

github:
  repo:           https://github.com/craigeley/fieldnoise-site

gems:
  - jekyll-paginate
  - jekyll-gist
  - pygments.rb
  
disqusid: fieldnoise

prose:
    rooturl: '_posts'
    metadata:
        _posts:
          - name: "layout"
            field:
              element: "hidden"
              value: "post"
          - name: "tags"
            field:
              element: "multiselect"
              label: "Add Tags"
              placeholder: "Add Tags"
              alterable: true
          - name: "title"
            field:
              element: "text"
              label: "Post title"
              placeholder: "Title"
              alterable: true